### ISSUE TITLE
아니?!

### ISSUE THREAD

**Issue by d-h-k** [KimMinJoon/KimMinJoon#1]
아니?!?!? 나닛?!?!?!?

자기소개 빠진거 있음

I'm 판교의 rich rich BBoy ~  << 이런 코드가 한줄 추가되야 힙할꺼같음

**Comment by KimMinJoon** [comment]
> 아니?!?!? 나닛?!?!?!?
> 
> 자기소개 빠진거 있음
> 
> I'm 판교의 rich rich BBoy ~ << 이런 코드가 한줄 추가되야 힙할꺼같음

**Comment by KimMinJoon** [comment]
하나 빠지긴했네 나의 뢀모들 갓동후이

**Comment by d-h-k** [comment]
앗 깃허브 답장이 빠른 이남자.. 매력이따  👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by KimMinJoon** [comment]
이렇게 노는 남우형 갓동훈 ㅋㅋㅋㅋ 따라해봤는데 이것만의 매력이 있네~~~
